### ISSUE TITLE
Question on bbmap files for multiqc

### ISSUE THREAD

**Issue by aschuerch** [boulund/MultiQC_bbmap#1]
Apologies if I am not posting in the right repo but this refers to the bbmap module pull request. I run multiqc version 1.3 as a bioconda package but I seem unable to make multiqc recognize my bbmap output files, neither with or without the -tag bbmap. Is there a naming convention for bbmap output files to be recognized by multiqc?

**Comment by boulund** [comment]
Hi! 

I think this question is actually best asked directly in the official [MultiQC repository](https://github.com/ewels/MultiQC), but no worries, I created an issue there, so let's continue the discussion over [here](https://github.com/ewels/MultiQC/issues/621)
